# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a364577774f0d1756a850fdc933f1391b4964c0d45689397b9756f6186d12bedd55e0e269a2a438f050188bc3e106e65206f9e697d958669e0a94b3a5d36fa3b

test:
  secret_key_base: ccc5bf371381b8a5596bf1533197a9333b9a926431a4e85682f2c1ee44475182534d97c37821cb8d9dcb1b28f2cec8e164ada2998758a9f4d58a1556866047a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
